name: Publish NuGet.org

on:
  push:
    branches: 
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    name: Update package

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 6.0.x

      - name: Building
        run: |
          dotnet build MathCore.WebAPIClients -c Release --nologo
#          dotnet build Tests/MathCore.WebAPIClients.Tests -c Release --nologo

#       - name: Testing
#         run: dotnet test Tests/MathCore.WebAPIClients.Tests -c Release --no-build --nologo

      - name: Packing
        run: dotnet pack MathCore.WebAPIClients -c Release --no-build -v m
         
      - name: Publishing
        run: dotnet nuget push "**/*.nupkg" -k ${{ secrets.NuGetApiKey }} --skip-duplicate -s https://api.nuget.org/v3/index.json
